---
name: Classic CI/CD

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: EditorConfig-Action
        uses: greut/eclint-action@v0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: .yamllint.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # The Go version to download (if necessary) and use.
          go-version: 1.14
      - uses: actions/cache@v3.0.11
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install golangci-lint
        run: |
          curl -sSfL \
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.30.0

      - run: go run mage.go -v golang:staticTests
      - uses: ynniss/golang-security-action@master
